### ISSUE TITLE
np.maximum instead of np.max

### ISSUE THREAD

**Issue by alesolano** [pranshushah/cifar-10_resnet_tensorflow#1]
For the line `std = np.max([np.std(x[i, ...]), 1.0/np.sqrt(32 * 32 * 3)])'`,
I think you should use `np.maximum` (https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html) instead of `np.max` or `np.amax` (https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html).

**Comment by pranshushah** [comment]
hy there, i used different kind of pre processing step you can check out   cifar10_resnet_identity.ipynb notebook and thanks for pointing me out my mistake and please tell me whether is this correct or not
